# Generated by Django 5.1.3 on 2024-11-19 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0019_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("CronTaskType", "Cron Task"),
                    ("RepeatableTaskType", "Repeatable Task"),
                    ("OnceTaskType", "Run once"),
                ],
                default="OnceTaskType",
                max_length=32,
                verbose_name="Task type",
            ),
        ),
    ]
