# Generated by Django 6.1.1 on 2026-09-10 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0021_remove_task_job_id_task_job_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskarg',
            name='arg_type',
            field=models.CharField(choices=[('str', 'string'), ('int', 'int'), ('float', 'float'), ('bool', 'boolean'), ('datetime', 'datetime'), ('json', 'JSON'), ('callable', 'callable')], default='str', max_length=12, verbose_name='Argument Type'),
        ),
        migrations.AlterField(
            model_name='taskarg',
            name='val',
            field=models.CharField(blank=True, max_length=2048, verbose_name='Argument Value'),
        ),
        migrations.AlterField(
            model_name='taskkwarg',
            name='arg_type',
            field=models.CharField(choices=[('str', 'string'), ('int', 'int'), ('float', 'float'), ('bool', 'boolean'), ('datetime', 'datetime'), ('json', 'JSON'), ('callable', 'callable')], default='str', max_length=12, verbose_name='Argument Type'),
        ),
        migrations.AlterField(
            model_name='taskkwarg',
            name='val',
            field=models.CharField(blank=True, max_length=2048, verbose_name='Argument Value'),
        ),
    ]
